### ISSUE TITLE
elasticsearch throws error: Connection reset by peer

### ISSUE THREAD

**Issue by grenwi** [hoover/search#31]
When indexing a collection, after ca. 74000 documents the process for 

`docker-compose run --rm search ./manage.py update -v2 mycollection`

suddenly stops with this error message:

```
2018-02-08 12:33:35 1 INFO hoover.search.index updating <Collection: mycollection>                                                                                                                                       
2018-02-08 12:33:35 1 INFO hoover.search.index resuming load: {'feed_state': 'http://snoop/htmidi/feed?lt=2018-02-07T04:20:59.559099Z', 'report': {'indexed': 74000}}                                              
2018-02-08 12:34:00 1 WARNING elasticsearch POST http://search-es:9200/_bulk [status:N/A request:1.140s]                                                                                                           
Traceback (most recent call last):                                                                                                                                                                                 
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen                                                                                                                    
    chunked=chunked)                                                                                                                                                                                               
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 356, in _make_request                                                                                                              
    conn.request(method, url, **httplib_request_kw)                                                                                                                                                                
  File "/usr/local/lib/python3.6/http/client.py", line 1239, in request                                                                                                                                            
    self._send_request(method, url, body, headers, encode_chunked)                                                                                                                                                 
  File "/usr/local/lib/python3.6/http/client.py", line 1285, in _send_request                                                                                                                                      
    self.endheaders(body, encode_chunked=encode_chunked)                                                                                                                                                           
  File "/usr/local/lib/python3.6/http/client.py", line 1234, in endheaders                                                                                                                                         
    self._send_output(message_body, encode_chunked=encode_chunked)                                                                                                                                                 
  File "/usr/local/lib/python3.6/http/client.py", line 1065, in _send_output                                                                                                                                       
    self.send(chunk)                                                                                                                                                                                               
  File "/usr/local/lib/python3.6/http/client.py", line 986, in send                                                                                                                                                
    self.sock.sendall(data)                                                                                                                                                                                        
ConnectionResetError: [Errno 104] Connection reset by peer
```

I assume, there is a very large file in mycollection causing this error.

As a workaround, a max document size could be introduced or a large file split into several pieces.

**Comment by mgax** [comment]
Hi @grenwi, what does the elasticsearch log say?

**Comment by grenwi** [comment]
Not easy to say. I am running the docker setup which does not log anything by default. I need to find out how to get the log running... any suggestions?

**Comment by mgax** [comment]
Yes, you can look at the docker logs with `docker-compose logs -f search-es`.

**Comment by grenwi** [comment]
Alright, yes, the logs show the presumed error:

```
search-es_1   | org.jboss.netty.handler.codec.frame.TooLongFrameException: HTTP content length exceeded 104857600 bytes.
search-es_1   |   at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:169)
search-es_1   |   at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
search-es_1   |   at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
search-es_1   |   at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
search-es_1   |   at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:135)
search-es_1   |   at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
search-es_1   |   at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
search-es_1   |   at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
search-es_1   |   at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
search-es_1   |   at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
search-es_1   |   at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
search-es_1   |   at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
search-es_1   |   at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
search-es_1   |   at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
search-es_1   |   at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
search-es_1   |   at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
```
Unfortunately, I cannot see from the logs which file caused the error. But the collection contains a very diverse set of files, among other server logs which might exceed the frame limit.

I suppose that for most of such error cases it would be fine to cut the to-be-indexed content to the allowed frame length. But maybe there is a more elegant solution?

**Comment by mgax** [comment]
I'd question the usefulness of indexing a 100GB file. At some point the database/index must impose some limits on data size. If cutting the content is acceptable, we can do that somewhere in snoop, before the data gets sent off to elasticsearch. Bonus points if we flag the document so the user knows it's been truncated.

**Comment by gabriel-v** [comment]
No updates on the issue, closing
